[Back to Index](../index.html)

If $b = Ax$, then $b$ is a linear combination of the columns of $A$ using components of x as weights.

If A is invertible, then $x = A^{-1}b$.
where, $A^{-1}$ is the inverse of $A$.

If A is not invertible, then $x = A^+b$.
where, $A^+$ denotes the Moore-Penrose pseudoinverse of A. The pseudoinverse allows for the computation of a solution to the system of linear equations even when A is not invertible

In [4]:
import numpy as np
import matplotlib.pyplot as plt

### Matrix-vector multiplication Use case - Markov Chain

In a Markov chain, the probability of transitioning to a future state depends only on the current state and not on the sequence of events that preceded it. This can be illustrated with a simple two-state Markov chain representing the weather as rainy or sunny.

Let's define the transition matrix P, where P(i, j) represents the probability of transitioning from state i to state j. In this case, the states are "rainy" and "sunny". The transition matrix is given by:

$$
P = \begin{bmatrix}
0.5 & 0.5 \\
0.4 & 0.6
\end{bmatrix}
$$


This means that if it is rainy today, the probability of it being rainy tomorrow is 0.5, and the probability of it being sunny tomorrow is 0.5. If it is sunny today, the probability of it being rainy tomorrow is 0.4, and the probability of it being sunny tomorrow is 0.6.

To find the probability of the weather being rainy or sunny on the next day, we can use the current probabilities of the weather being rainy or sunny and the transition matrix. If the current probabilities are represented by a row vector $$\pi = [\pi_{\text{rainy}}, \pi_{\text{sunny}}]$$, then the probabilities for the next day are given by:

$$
\pi^{(1)} = \pi \times P
$$


The matrix-vector multiplication correctly gives the next state probabilities due to the properties of the transition matrix and the interpretation of the multiplication operation. When we perform the multiplication $\pi \times P$, each element in the resulting vector $\pi^{(1)}$ represents the weighted sum of the transition probabilities from the current states to all possible next states. This aligns with the fundamental concept of Markov chains, where the next state probabilities are determined by the current state and the transition probabilities.

The probability of the next state being rainy is given by the matrix-vector multiplication:

$$
\begin{aligned}
P(\text{next state = rainy}) & = P(\text{current state = rainy}) \times P(\text{rainy} | \text{rainy}) + P(\text{current state = sunny}) \times P(\text{rainy} | \text{sunny}) \\
& = \pi \times \begin{bmatrix} 0.5 & 0.5 \\ 0.4 & 0.6 \end{bmatrix}
\end{aligned}
$$


And the probability of the next state being sunny is given by:

$$
\begin{aligned}
P(\text{next state = sunny}) & = P(\text{current state = rainy}) \times P(\text{sunny} | \text{rainy}) + P(\text{current state = sunny}) \times P(\text{sunny} | \text{sunny}) \\
& = \pi \times \begin{bmatrix} 0.5 & 0.5 \\ 0.4 & 0.6 \end{bmatrix}
\end{aligned}
$$



In [39]:
# Probabilities of moving from 1 health state to another in 1 year
A = np.array(
    [
        [0.9, 0.07, 0.02, 0.01],
        [0, 0.93, 0.05, 0.02],
        [0, 0, 0.85, 0.15],
        [0, 0, 0, 1]
    ]
)
print(f"A is \n{A}\n") # A_ij = probability of moving from health state i to health state j in 1 year


# Current Health States
x = np.array([0.85, 0.1, 0.05, 0])
print(f"x is {x}\n") # x_i = probability of being in health state i now

## To find probabilities of being in each health state in 1 year, 
## the formula to find the probability of being in health state j in 1 year is: 
## x_j = sum_i(x_i * A_ij)
## where x_i is the probability of being in health state i now,
## and A_ij is the probability of moving from health state i to health state j in 1 year

x_next = x @ A #  (x @ A).T by default, numpy does broadcasting but to be strict, we can transpose 

# other way to do it is A.T @ x.T

x_next.shape
print(f"x_next is {x_next}") # x_next_j = probability of being in health state j in 1 year

A is 
[[0.9  0.07 0.02 0.01]
 [0.   0.93 0.05 0.02]
 [0.   0.   0.85 0.15]
 [0.   0.   0.   1.  ]]

x is [0.85 0.1  0.05 0.  ]

x_next is [0.765  0.1525 0.0645 0.018 ]
